baseURL = 'https://fabshkiee.github.io/hugo-theme-erudite/'
locale = 'en-us'
title = 'Fabshkiee'
theme = 'hugo-theme-erudite'
themesDir = '../..'

[params]
  description = "Role · Hobbyist · Creator"
  mainSections = ["blog"]

[params.author]
  name = "Your Name"
  role = "Your Role @ Company"
  avatar = "https://github.com/ghost.png"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 30

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/Fabshkiee"
  weight = 10

[[menu.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/Fabshkiee"
  weight = 20
